@mainClass "inv_fail_inherited_catched::Main"
@mainOperation "main"


package inv_fail_inherited_catched;

require kermeta

using kermeta::kunit
using kermeta::standard
using kermeta::exceptions

class Main inherits superMain, superMain2, TestCase
{
    inv titi is  do str == "titi" end
    inv toto is do true end

	reference str : String 

    operation main() : Void is do
    	var tr : TestRunner init TestRunner.new
		tr.run(Main)
		tr.printTestResult
    end

    
    method setUp() : Void is do
        str := "titi"
        superstr := "supertiti"
        superstr2 := "supertiti2"
    end
    
    operation test0() is do
    
		do
        	self.checkInvariants
        	assert(true) 
        rescue (err : ConstraintViolatedInv)
        	assert(false)
        	stdio.writeln(err.toString)
        	stdio.writeln(err.message)
        end
        
        // to make the invariant failed
        superstr := "not supertiti"
        do
        	self.checkInvariants
        	assert(false)
        rescue (err : ConstraintViolatedInv)
        	stdio.writeln(err.toString)
        	stdio.writeln(err.message)
        	assert(true)
        end
        
        superstr := "supertiti"
        
		do
        	self.checkInvariants
        	assert(true) 
        rescue (err : ConstraintViolatedInv)
        	assert(false)
        	stdio.writeln(err.toString)
        	stdio.writeln(err.message)
        end
    end
    
}

class superMain
{
	reference superstr : String
	
	inv superMainInv is superstr == "supertiti"
}

class superMain2
{
	reference superstr2 : String
	
	inv superMain2Inv is do superstr2 == "supertiti2" end
}