@mainClass "inv_redefinition_is_in_fact_union_fail_partly_catched::Main"
@mainOperation "main"


package inv_redefinition_is_in_fact_union_fail_partly_catched;

require kermeta

using kermeta::standard
using kermeta::exceptions
using kermeta::kunit

class Main inherits superMain, superMain2, TestCase
{
    inv titi is  do str == "titi" end
    inv toto is do true end
	inv toBeRedefined is superstr == "supertiti_redined"
	
	reference str : String 

    operation main() : Void is do
    	var tr : TestRunner init TestRunner.new
		tr.run(Main)
		tr.printTestResult
    end

    operation test0() : Void is 
     do
        str := "titi"
        superstr := "supertiti"
        superstr2 := "supertiti2"
		do
        	self.checkInvariants 
        	assert(false)
        rescue (err : ConstraintViolatedInv)
        	stdio.writeln(err.toString)
        	stdio.writeln(err.message)
        	assert(true)
        end
        
    end
}

class superMain
{
	reference superstr : String
	
	inv toBeRedefined is superstr == "supertiti"
}

class superMain2
{
	reference superstr2 : String
	
	inv superMain2Inv is do superstr2 == "supertiti2" end
}